[package]
name = "rust-diesel-orm"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.0"
actix-web = "4.2.1"
chrono = "0.4.38"
diesel = { version = "2.2.2", features = ["postgres", "r2d2"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
